### ISSUE TITLE
do you mean tempData instead of tempdata?

### ISSUE THREAD

**Issue by vinnitu** [ignoreintuition/websocket#1]
https://github.com/ignoreintuition/websocket/blob/22610eb3701963d0b05a795737b8e96f4d999d4a/http/js/main.js#L32

**Comment by ignoreintuition** [comment]
Yes.  Feel free to updated and send a PR.

**Comment by vinnitu** [comment]
No. Maybe just splice() because it is inline operation

```javascript
tempData.splice(0, 1); 
```
